### ISSUE TITLE
Small changes to add flexibility

### ISSUE THREAD

**Issue by racosgrove** [timo-reymann/python-oauth2-cli-auth#11]
### Description

This is a great little library that does almost exactly what I need.   Can I suggest 2 small changes that would improve the overall usability.

- Firstly remove the print() statement in `open_browser()` function or turn it into a log.  Being an uncontrolled output it makes it harder to work with this library in a script where the only desired output is the access token itself.

- Allow `exchange_code_for_access_token()` to optionally return the entire JSON payload.  This way a refresh token and other meta can be captured as well.

Kind regards
Rob

**Comment by timo-reymann** [comment]
Hi Rob,

Foremost, thanks for giving the lib a shot! :) 

Appreciate the feedback, some very valid points, I will gladly add to the lib.

Cheers
Timo

**Comment by timo-reymann** [comment]
API changes are released with [1.3.0](https://github.com/timo-reymann/python-oauth2-cli-auth/releases/tag/1.3.0).

I did not change the “convenience methods”, as they are intended to be used for simple use-cases and can easily be put together as a composition.
